create sequence hibernate_sequence start 1 increment 1;

create table message
(
    id       int8 not null,
    announce text,
    color    varchar(255),
    date     timestamp,
    filename varchar(255),
    text     text,
    title    text,
    viewers  int8,
    user_id  int8,
    primary key (id)
);

create table message_likes
(
    message_id int8 not null,
    user_id    int8 not null,
    primary key (message_id, user_id)
);

create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

create table usr
(
    id          int8         not null,
    active      boolean      not null,
    email       varchar(255),
    password    varchar(255) not null,
    profile_pic varchar(255),
    username    varchar(16)  not null,
    primary key (id)
);

create table usr_profiles
(
    id           int8 generated by default as identity,
    dob          timestamp,
    gender       varchar(10),
    phone_number varchar(255),
    user_id      int8 not null,
    primary key (id)
);

alter table if exists user_role
    add constraint user_role_user_fk
        foreign key (user_id) references usr;

alter table if exists usr_profiles
    add constraint user_profile_fk
        foreign key (user_id) references usr;

alter table if exists usr_profiles
    add constraint user_profile_unique
        unique (user_id);

alter table if exists message
    add constraint message_fk
        foreign key (user_id) references usr;

alter table if exists message_likes
    add constraint message_likes_user_fk
        foreign key (user_id) references usr;

alter table if exists message_likes
    add constraint message_likes_message_fk
        foreign key (message_id) references message;
